<div class="pheader clearfix"><?php echo isset($aAnswer['iAutoID'])?'编辑':'增加'?>答案</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="/admin/question/answersave.html">

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">
                <span style="color:red;">*</span>&nbsp;答案：</label>
            <div class="col-sm-8">
                <input type="text" id="sAnswer" validate="!length:1-100" value="<?php echo $aAnswer['sAnswer']?>" name="sAnswer" class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">答案后续问题：</label>
            <div class="col-sm-8">
                <input type="text" value="<?php echo $aAnswer['aNext']['iAutoID'] ? $aAnswer['aNext']['iAutoID'].'.' : ''?><?php echo $aAnswer['aNext']['sTitle']?>" id="sNextQuestion" name="sNextQuestion" source="/admin/question/nextquestion.html" ivalue="sTitle" ishow="item.sTitle" iresult="#iNextID=iAutoID" class="form-control input-validate yyauto ui-autocomplete-input" autocomplete="off">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <input type="hidden" value="<?php echo $iQuestionID?>" name="iBelongID">
        <input type="hidden" value="<?php echo $aAnswer['iNextID']?>" name="iNextID" id="iNextID">
        <input type="hidden" value="<?php echo $aAnswer['iAutoID']?>" name="iAnswerID">

        <div class="form-group">
            <label class="col-sm-2 control-label">问题标签：</label>

            <div class="col-sm-10">
                <input type="hidden" name="sTag" id="sTag"
                       value="<?php echo isset($aAnswer['sTag']) ? $aAnswer['sTag'] : '' ?>">
                <?php $aAnswerTag = isset($aAnswer['sTag']) ? explode(',', $aAnswer['sTag']) : [] ?>
                <div style="float:left;width:70%">
                    <div class="clear"></div>
                    <div class="selestbeizhu">
                        <span style="float:left;">可选10个标签：</span>

                        <div id="questionTagSelect" style="">
                            <?php if (isset($aAnswer['aTag'])) {
                                foreach ($aAnswer['aTag'] as $answerTag) {?>
                                    <a href="javascript:void(0);" class="des_post" rel="<?=$answerTag['iTypeID']?>"><span><?php echo $answerTag['sTypeName'] ?></span><i
                                            class="fa fa-remove"></i></a>
                            <?php }} ?>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="selestbeizhu">
                    <select onchange="onTagSelect(this.value);">
                        <?php foreach ($aTag as $key => $value) { ?>
                            <option value="<?php echo $value['iTypeID']?>"><?php echo $value['cat']?></option>
                        <?php }?>
                    </select>
                    </div>
                    <?php $i = 1;?>
                    <?php foreach($aTag as $key => $value){?>
                    <div class="selestxuanze questiontags" id="tags<?php echo $value['iTypeID']?>" <?php if ($i != 1){?>style="display:none"<?php }?>>
                        <?php foreach ($value['aTags'] as $iTagID => $sTag) { ?>
                            <a href="javascript:void(0)" rel="<?=$sTag['iTypeID'];?>" <?php
                            if (isset($aAnswerTag) && in_array($sTag['iTypeID'], $aAnswerTag)) {
                                echo "class='gray'";
                            }
                            ?>><?php echo $sTag['sTypeName'] ?></a>
                        <?php } ?>
                        <?php $i++;?>
                    </div>
                    <?php }?>
                </div>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">文案内容：</label>
            <div class="col-sm-10">
                <textarea name="sDesc" class="form-control input-validate"><?php echo isset($aAnswer['sDesc'])?$aAnswer['sDesc']:''?></textarea>
                <span class="validate_checktip"></span>
            </div>
        </div>

    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/question/answer.html?id=<?php echo $iQuestionID?>';return false;">取消</button>
        </div>
	</form>
</div>
<link rel="stylesheet" href="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.css" type="text/css"/>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.js"></script>
<script>

function onTagSelect(id) {
    $('.questiontags').each(function(){
        $(this).hide();
    });
    $('#tags'+id).show();
}

$(function() {
    loadAuto();

    $("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '/admin/question/answer.html?id=<?php echo $iQuestionID?>';
	        }
	    }, 'json');
		return false;
	}});


    //标签操作
    $('.questiontags a').click(function () {
        if ($(this).hasClass('gray')) {
            return false;
        }
        var val = $('#sTag').val();
        if (val.split(',').length == 10) {
            alert('只能添加十个标签！');
            return false;
        }
        val = val.length == 0 ? $(this).prop('rel') : val + ',' + $(this).prop('rel');
        $('#sTag').val(val);

        var str = '<a href="javascript:void(0);" class="des_post" rel="' + $(this).prop('rel') + '"><span>' + $(this).html() + '</span><i class="fa fa-remove"></i></a>';
        $('#questionTagSelect').append($(str));
        $(this).addClass('gray');
        $('#questionTagSelect a').click(delNewsTag);
    });

    $('#questionTagSelect a').click(delNewsTag);
    function delNewsTag() {
        var str = $(this).prop('rel');
        var vals = $('#sTag').val().split(',');
        for (var i = 0; i < vals.length; i++) {
            if (vals[i] == str) {
                vals.splice(i, 1);
                break;
            }
        }
        $('#sTag').val(vals.join(','));
        $(this).remove();
        $('.questiontags a').each(function () {
            if ($(this).prop('rel') == str) {
                $(this).removeClass('gray');
            }
        })
    }
});

    function loadAuto() {
        var fileref = document.createElement('script');
        fileref.setAttribute("type","text/javascript");
        fileref.setAttribute("src",'<?php echo $sStaticRoot ?>/js/autocomplete.js');
        document.getElementsByTagName("head")[0].appendChild(fileref);
    }
</script>