<div class="pheader clearfix">问题库</div>
<div class="pbody clearfix">
    <div class="btn-toolbar list-toolbar">
    	<button class="btn btn-primary" id="question_add">
    		<i class="fa fa-plus"></i> 增加问题
    	</button>
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
                <th>问题</th>
                <th>分类</th>
                <th>标签</th>
    			<th>说明</th>
                <th>提示</th>
                <th>创建时间</th>
                <th>修改时间</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $aQuestion) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $aQuestion['iAutoID']?></td>
                <td><?php echo $aQuestion['sTitle']?></td>
                <td><?php if ($aQuestion['aCategory']) { echo $aQuestion['aCategory']['sTypeName'];} else { echo '';}?></td>

                <td><?php if ($aQuestion['aTag']) {
                        foreach($aQuestion['aTag'] as $aTag) {
                            echo $aTag['sTypeName'].',';
                        }
                    } else {
                        echo '';
                    }?></td>
    			<td><?php echo $aQuestion['sDesc']?></td>
                <td><?php echo $aQuestion['sTips']?></td>
                <td><?=date('Y-m-d H:i:s', $aQuestion['iCreateTime'])?></td>
                <td><?=date('Y-m-d H:i:s', $aQuestion['iUpdateTime'])?></td>
    			<td class="text-center">
                    <a href="/admin/question/answer.html?id=<?php echo $aQuestion['iAutoID']?>" title="问题答案"><i class="fa fa-list-ul fa-large"></i></a>
    			    <a href="/admin/question/edit.html?id=<?php echo $aQuestion['iAutoID']?>" title="编辑"><i class="fa fa-pencil fa-large"></i></a>
    			    <a class="question_delete" href="/admin/question/del.html?id=<?php echo $aQuestion['iAutoID']?>" title="删除"><i class="fa fa-trash fa-large"></i></a>
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>
<script>
$('.question_delete').click(function() {
	var url = this.href;
	if (confirm("您确认要删除该问题吗？")) {
		$.get(url, function(ret){
			alert(ret.data);
			if (ret.status) {
				location.reload();
			}
		}, 'json');
	}
	return false;
});
$('#question_add').click(function(){
	location.href = '/admin/question/add.html';
});
</script>