<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"   content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-touch-fullscreen" content="yes"  />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta content="包大状" name="keywords" />
    <meta content="包大状" itemprop="description" name="description" />
    <title>包大状<?php echo !empty($title) ? '-'.$title : ''?></title>
    <link rel="stylesheet" href="<?php echo $sStaticRoot?>/static/css/common.css" />
    <script type='text/javascript' src='<?php echo $sStaticRoot ?>/static/js/zepto.min.js' charset='utf-8'></script>
    <script src="<? echo $sStaticRoot?>/static/js/common.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>
<?php include $_script;?>
</body>
</html>
