<div class="pheader clearfix">微信用户列表</div>
<div class="pbody clearfix">
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th class="text-center">微信名称</th>
    			<th class="text-center">性别</th>
    			<th class="text-center">国家</th>
    			<th class="text-center">省</th>
    			<th class="text-center">城市</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $aUser) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $aUser['iUserID']?></td>
    			<td class="text-center"><?php echo $aUser['sName']?></td>
    			<td class="text-center"><?php echo $aUser['sSex'] == 1 ? '男' : ($aUser['sSex'] == 2 ? '女' : '未知')  ?></td>
    			<td class="text-center"><?php echo $aUser['sCountry']?></td>
    			<td class="text-center"><?php echo $aUser['sProvince']?></td>
    			<td class="text-center"><?php echo $aUser['sCity']?></td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>