<div class="pheader clearfix">咨询模板发送管理</div>
<div class="pbody clearfix">
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="col-sm-1 text-center">#</th>
            <th>婚姻手册</th>
            <th>Email</th>
            <th>是否发送</th>
            <th>创建时间</th>
            <th>修改时间</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($aList['aList'] as $value) {?>
            <tr>
                <td class="col-sm-1 text-center"><?php echo $value['iAutoID']?></td>
                <td><?php echo $value['article']['sTitle']?></td>
                <td><?php echo $value['sEmail']?></td>
                <td><?php echo $value['iSend'] == 2 ? '已发送' : '未发送'?></td>
                <td><?=date('Y-m-d H:i:s', $value['iCreateTime'])?></td>
                <td><?=date('Y-m-d H:i:s', $value['iUpdateTime'])?></td>
                <td class="text-center">
                    <a href="/admin/article/send.html?id=<?php echo $value['iAutoID']?>" role="button" class="type_send" title="发送模板"><i class="fa fa-pencil fa-large"></i></a>
                </td>
            </tr>
        <?php }?>
        </tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>
<script>
    $('.type_send').click(function() {
        var url = this.href;
        if (confirm("你确定已发送吗？")) {
            $.get(url, function(ret){
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
        return false;
    });
</script>