<div class="pheader clearfix">交易数据导入</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="text-red">*</span> 上传城市：</label>
            <div class="col-sm-10">
                <select name="iCityID" class="form-control input-validate">
                    <?php foreach ($__aCityList__ as $k => $v) { ?>
                        <option value="<?php echo $k ?>"><?php echo $v ?></option>
                    <?php } ?>
                </select>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="red">*</span> 上传文件：</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control input-validate" validate="*required:请上传文件" id="sFile" name="sFile"">
                <input type="button" value="选择" class="plupload btn btn-primary" data-target="#sFile" data-fsize="100mb" data-ext="xlsx,xls">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="btn-toolbar text-center col-sm-9 publish-div">
            <button id="save" class="btn btn-primary">确认</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/trade/list.html';return false;">取消</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    global.sUploadUrl = '<?php echo Yaf_G::getConf('upload', 'url')?>';
    global.sDfsViewUrl = '<?php echo Yaf_G::getConf('dfsview', 'url')?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/plupload/zh_CN.js"></script>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            //location.href = '/admin/trade/';
	        }
	    }, 'json');
		return false;
	}});
});
</script>