<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"   content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-touch-fullscreen" content="yes"  />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta content="包大状" name="keywords" />
    <meta content="包大状" itemprop="description" name="description" />
    <meta content="包大状" name="keywords" />
    <meta content="包大状" itemprop="description" name="description" />
    <title>包大状介绍</title>
    <link rel="stylesheet" href="<?php echo $sStaticRoot?>/static/css/swiper-3.3.1.min.css" />
    <link rel="stylesheet" href="<?php echo $sStaticRoot?>/static/css/animate.css" />
    <link rel="stylesheet" href="<?php echo $sStaticRoot?>/static/css/h5introduce.css" />
    <script src="<?php echo $sStaticRoot?>/static/js/swiper-3.3.1.min.js" type="text/javascript" charset="utf-8" ></script>
    <script src="<?php echo $sStaticRoot?>/static/js/swiper.animate1.0.2.min.js" type="text/javascript" charset="utf-8" ></script>
    <script src="<?php echo $sStaticRoot?>/static/js/common.js" type="text/javascript" charset="utf-8" async defer></script>
</head>
<body>

<!-- Swiper -->
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide slideone">
            <div class="topfont ani" swiper-animate-effect="fadeInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s"></div>
            <div class="bottomPhone ani" swiper-animate-effect="slideInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.6s"></div>
            <div class="iconflag ani" swiper-animate-effect="fadeInRight" swiper-animate-duration="0.5s" swiper-animate-delay="0.8s"></div>

        </div>
        <div class="swiper-slide slidetwo">
            <div class="topfont ani" swiper-animate-effect="fadeInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s"></div>
            <div class="bottomPhone ani" swiper-animate-effect="slideInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.6s"></div>
        </div>
        <div class="swiper-slide slidethrid">
            <div class="topfont ani" swiper-animate-effect="fadeInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s"></div>
            <div class="bottomPhone ani" swiper-animate-effect="slideInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.6s"></div>
            <div class="iconflag ani" swiper-animate-effect="fadeInRight" swiper-animate-duration="0.5s" swiper-animate-delay="0.8s"></div>
        </div>
        <div class="swiper-slide slidefour">
            <div class="topfont ani" swiper-animate-effect="fadeInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s"></div>
            <div class="bottomPhone ani" swiper-animate-effect="slideInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.6s"></div>
        </div>
        <div class="swiper-slide slidefive">
            <div class="topfont ani" swiper-animate-effect="fadeInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s"></div>
            <div class="bottomPhone ani" swiper-animate-effect="slideInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.6s"></div>
            <div class="iconflag ani" swiper-animate-effect="fadeInLeft" swiper-animate-duration="0.5s" swiper-animate-delay="0.8s"></div>
        </div>
    </div>
    <!-- Add Pagination -->
</div>
<script>
    var swiper = new Swiper('.swiper-container', {
        direction: 'vertical',
        loop: true,
        onInit: function(swiper){ //Swiper2.x的初始化是onFirstInit
            swiperAnimateCache(swiper); //隐藏动画元素
            swiperAnimate(swiper); //初始化完成开始动画
        },
        onSlideChangeEnd: function(swiper){
            swiperAnimate(swiper); //每个slide切换结束时也运行当前slide动画
        }
    });
</script>

</body>
</html>